#https://github.com/corderun
#Placheolders: %player% - nickname, %amount% - amount of prize
messages:
  no-perm: '&cYou dont have permission to do that!'
  reload: '&fSuccessful reload!'
  reward: '&fYou received &e%amount% &fbonus!'
mobs:
  #Name of mob (CapsLock required)
  ZOMBIE:
    #The command to be executed after a kill
    command: 'give %player% minecraft:diamond %amount%'
    #Amount of reward given after a kill (Needed for action bar)
    amount: 5
  CREEPER:
    command: 'give %player% minecraft:emerald %amount%'
    amount: 3
  #You can write here any mobs